PKGDIR       ?= ../..
L4DIR        ?= $(PKGDIR)/../..

TARGET	      = lib_i2c_server.a lib_i2c_server.so
SRC_CC        = i2c_server.cc
PC_FILENAME   = lib_i2c_server
REQUIRES_LIBS = libstdc++ l4virtio

include $(L4DIR)/mk/lib.mk
