PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

# the name of your library
TARGET	= lib_i2c_server.a

# list your .c or .cc files here
SRC_C	= 
SRC_CC  =

PC_FILENAME = lib_i2c_server

include $(L4DIR)/mk/lib.mk
